<a href="https://colab.research.google.com/github/akshitaasaxena/python-ds/blob/main/day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#leetcode 1757
import pandas as pd

def find_products(products: pd.DataFrame) -> pd.DataFrame:
    return products.loc[
    (products['low_fats'] == 'Y') & (products['recyclable'] == 'Y'),
    ['product_id']]

In [ ]:
#leetcode 584
import pandas as pd

def find_customer_referee(customer: pd.DataFrame) -> pd.DataFrame:
    return customer.loc[customer['referee_id'].isna() | (customer['referee_id']!=2),['name']]

In [ ]:
#leetcode 595
import pandas as pd

def big_countries(world: pd.DataFrame) -> pd.DataFrame:
    return world.loc[(world['area']>=3000000)|(world['population']>=25000000),['name','population','area']]

# GROUP-BY

In [ ]:
import pandas as pd
df=pd.read_csv('student_data.csv')
df.groupby('placement_status')['placement_status'].agg('count')

placement_status
Not Placed    1644
Placed        8356
Name: placement_status, dtype: int64

syntax: df.groupby('kis column by group by')[kis column pe operation perform krna hai'].agg(function)

zaruri nahi hai ki kis pe lagana hai aur jispe operation erformm krna ho vo same ho

In [ ]:
df.groupby('placement_status')['exam_score'].agg('mean')

placement_status
Not Placed    59.804653
Placed        91.996556
Name: exam_score, dtype: float64

In [ ]:
df.groupby('placement_status')['sleep_hours'].agg('mean')

placement_status
Not Placed    6.072384
Placed        6.582336
Name: sleep_hours, dtype: float64

In [ ]:
df.groupby('study_hours')['exam_score'].agg('mean')

study_hours
1     71.264562
2     75.169142
3     78.974939
4     81.845483
5     84.964142
6     88.620043
7     90.539568
8     93.297697
9     95.462126
10    96.574628
11    97.303283
Name: exam_score, dtype: float64

# APPLY FUNCTION

In [ ]:
def grades(c):
  if c>=90:
    return "a"
  elif c>=80:
    return "b"
  elif c>=70:
    return "c"
  else:
    return "fail"
print(grades(90))
df['grade']=df['exam_score'].apply(grades) # 'grade'= ye column ka name hai jo add hojayega, grades function ka name hai jo apply hoga
df

a

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,grade
0,7,56,8,7,10,62,100.00,Placed,a
1,4,69,5,3,8,56,100.00,Placed,a
2,11,60,7,6,10,45,100.00,Placed,a
3,8,99,9,8,4,55,90.17,Placed,a
4,5,52,8,6,8,40,78.82,Placed,c
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,fail
9996,7,98,6,9,4,87,100.00,Placed,a
9997,10,44,8,5,10,37,95.94,Placed,a
9998,10,75,7,5,8,52,88.61,Placed,b
9999,2,70,6,11,16,52,78.96,Placed,c

# join